alter table "public"."players" drop constraint "players_id_fkey";

alter table "public"."profiles" drop constraint "profiles_playerid_key";

alter table "public"."divisions" drop constraint "divisions_pkey";

drop index if exists "public"."profiles_playerid_key";

drop index if exists "public"."divisions_pkey";

create table "public"."teamplayers" (
    "team_id" bigint generated by default as identity not null,
    "player_id" bigint not null
);


alter table "public"."teamplayers" enable row level security;

create table "public"."teamtournaments" (
    "team_id" bigint generated by default as identity not null,
    "tournament_id" bigint,
    "division" text
);


alter table "public"."teamtournaments" enable row level security;

alter table "public"."divisions" drop column "id";

alter table "public"."divisions" add column "tournamentid" bigint generated by default as identity not null;

alter table "public"."divisions" alter column "name" set not null;

alter table "public"."stages" drop column "teams";

alter table "public"."stages" add column "division_name" text;

alter table "public"."stages" add column "name" text;

alter table "public"."teams" add column "name" text;

CREATE UNIQUE INDEX divisions_name_key ON public.divisions USING btree (name);

CREATE UNIQUE INDEX teamplayers_pkey ON public.teamplayers USING btree (team_id, player_id);

CREATE UNIQUE INDEX teamtournaments_pkey ON public.teamtournaments USING btree (team_id);

CREATE UNIQUE INDEX divisions_pkey ON public.divisions USING btree (tournamentid, name);

alter table "public"."teamplayers" add constraint "teamplayers_pkey" PRIMARY KEY using index "teamplayers_pkey";

alter table "public"."teamtournaments" add constraint "teamtournaments_pkey" PRIMARY KEY using index "teamtournaments_pkey";

alter table "public"."divisions" add constraint "divisions_pkey" PRIMARY KEY using index "divisions_pkey";

alter table "public"."divisions" add constraint "divisions_name_key" UNIQUE using index "divisions_name_key";

alter table "public"."divisions" add constraint "divisions_tournamentid_fkey" FOREIGN KEY (tournamentid) REFERENCES tournaments(id) not valid;

alter table "public"."divisions" validate constraint "divisions_tournamentid_fkey";

alter table "public"."stages" add constraint "stages_division_name_fkey" FOREIGN KEY (division_name) REFERENCES divisions(name) not valid;

alter table "public"."stages" validate constraint "stages_division_name_fkey";

alter table "public"."teamplayers" add constraint "teamplayers_player_id_fkey" FOREIGN KEY (player_id) REFERENCES players(id) not valid;

alter table "public"."teamplayers" validate constraint "teamplayers_player_id_fkey";

alter table "public"."teamplayers" add constraint "teamplayers_team_id_fkey" FOREIGN KEY (team_id) REFERENCES teams(id) not valid;

alter table "public"."teamplayers" validate constraint "teamplayers_team_id_fkey";

alter table "public"."teamtournaments" add constraint "teamtournaments_division_fkey" FOREIGN KEY (division) REFERENCES divisions(name) not valid;

alter table "public"."teamtournaments" validate constraint "teamtournaments_division_fkey";

alter table "public"."teamtournaments" add constraint "teamtournaments_team_id_fkey" FOREIGN KEY (team_id) REFERENCES teams(id) not valid;

alter table "public"."teamtournaments" validate constraint "teamtournaments_team_id_fkey";

alter table "public"."teamtournaments" add constraint "teamtournaments_tournament_id_fkey" FOREIGN KEY (tournament_id) REFERENCES tournaments(id) not valid;

alter table "public"."teamtournaments" validate constraint "teamtournaments_tournament_id_fkey";

grant delete on table "public"."teamplayers" to "anon";

grant insert on table "public"."teamplayers" to "anon";

grant references on table "public"."teamplayers" to "anon";

grant select on table "public"."teamplayers" to "anon";

grant trigger on table "public"."teamplayers" to "anon";

grant truncate on table "public"."teamplayers" to "anon";

grant update on table "public"."teamplayers" to "anon";

grant delete on table "public"."teamplayers" to "authenticated";

grant insert on table "public"."teamplayers" to "authenticated";

grant references on table "public"."teamplayers" to "authenticated";

grant select on table "public"."teamplayers" to "authenticated";

grant trigger on table "public"."teamplayers" to "authenticated";

grant truncate on table "public"."teamplayers" to "authenticated";

grant update on table "public"."teamplayers" to "authenticated";

grant delete on table "public"."teamplayers" to "service_role";

grant insert on table "public"."teamplayers" to "service_role";

grant references on table "public"."teamplayers" to "service_role";

grant select on table "public"."teamplayers" to "service_role";

grant trigger on table "public"."teamplayers" to "service_role";

grant truncate on table "public"."teamplayers" to "service_role";

grant update on table "public"."teamplayers" to "service_role";

grant delete on table "public"."teamtournaments" to "anon";

grant insert on table "public"."teamtournaments" to "anon";

grant references on table "public"."teamtournaments" to "anon";

grant select on table "public"."teamtournaments" to "anon";

grant trigger on table "public"."teamtournaments" to "anon";

grant truncate on table "public"."teamtournaments" to "anon";

grant update on table "public"."teamtournaments" to "anon";

grant delete on table "public"."teamtournaments" to "authenticated";

grant insert on table "public"."teamtournaments" to "authenticated";

grant references on table "public"."teamtournaments" to "authenticated";

grant select on table "public"."teamtournaments" to "authenticated";

grant trigger on table "public"."teamtournaments" to "authenticated";

grant truncate on table "public"."teamtournaments" to "authenticated";

grant update on table "public"."teamtournaments" to "authenticated";

grant delete on table "public"."teamtournaments" to "service_role";

grant insert on table "public"."teamtournaments" to "service_role";

grant references on table "public"."teamtournaments" to "service_role";

grant select on table "public"."teamtournaments" to "service_role";

grant trigger on table "public"."teamtournaments" to "service_role";

grant truncate on table "public"."teamtournaments" to "service_role";

grant update on table "public"."teamtournaments" to "service_role";

create policy "Enable insert for authenticated users only"
on "public"."divisions"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for all users"
on "public"."divisions"
as permissive
for select
to public
using (true);


create policy "Enable insert for authenticated users only"
on "public"."stages"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for all users"
on "public"."stages"
as permissive
for select
to public
using (true);


create policy "Enable insert for authenticated users only"
on "public"."teamplayers"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for all users"
on "public"."teamplayers"
as permissive
for select
to public
using (true);


create policy "Enable insert for authenticated users only"
on "public"."teams"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for all users"
on "public"."teams"
as permissive
for select
to public
using (true);


create policy "Enable insert for authenticated users only"
on "public"."teamtournaments"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for all users"
on "public"."teamtournaments"
as permissive
for select
to public
using (true);



