create table "public"."divisions" (
    "id" bigint generated by default as identity not null,
    "name" text,
    "size" bigint
);


alter table "public"."divisions" enable row level security;

create table "public"."players" (
    "id" bigint generated by default as identity not null
);


alter table "public"."players" enable row level security;

create table "public"."stages" (
    "id" bigint generated by default as identity not null,
    "tournamentid" bigint,
    "teams" bigint[]
);


alter table "public"."stages" enable row level security;

create table "public"."teams" (
    "id" bigint generated by default as identity not null
);


alter table "public"."teams" enable row level security;

alter table "public"."profiles" add column "playerid" bigint generated by default as identity not null;

CREATE UNIQUE INDEX divisions_pkey ON public.divisions USING btree (id);

CREATE UNIQUE INDEX players_pkey ON public.players USING btree (id);

CREATE UNIQUE INDEX profiles_playerid_key ON public.profiles USING btree (playerid);

CREATE UNIQUE INDEX stages_pkey ON public.stages USING btree (id);

CREATE UNIQUE INDEX teams_pkey ON public.teams USING btree (id);

alter table "public"."divisions" add constraint "divisions_pkey" PRIMARY KEY using index "divisions_pkey";

alter table "public"."players" add constraint "players_pkey" PRIMARY KEY using index "players_pkey";

alter table "public"."stages" add constraint "stages_pkey" PRIMARY KEY using index "stages_pkey";

alter table "public"."teams" add constraint "teams_pkey" PRIMARY KEY using index "teams_pkey";

alter table "public"."players" add constraint "players_id_fkey" FOREIGN KEY (id) REFERENCES profiles(playerid) not valid;

alter table "public"."players" validate constraint "players_id_fkey";

alter table "public"."profiles" add constraint "profiles_playerid_key" UNIQUE using index "profiles_playerid_key";

alter table "public"."stages" add constraint "stages_tournamentid_fkey" FOREIGN KEY (tournamentid) REFERENCES tournaments(id) not valid;

alter table "public"."stages" validate constraint "stages_tournamentid_fkey";

grant delete on table "public"."divisions" to "anon";

grant insert on table "public"."divisions" to "anon";

grant references on table "public"."divisions" to "anon";

grant select on table "public"."divisions" to "anon";

grant trigger on table "public"."divisions" to "anon";

grant truncate on table "public"."divisions" to "anon";

grant update on table "public"."divisions" to "anon";

grant delete on table "public"."divisions" to "authenticated";

grant insert on table "public"."divisions" to "authenticated";

grant references on table "public"."divisions" to "authenticated";

grant select on table "public"."divisions" to "authenticated";

grant trigger on table "public"."divisions" to "authenticated";

grant truncate on table "public"."divisions" to "authenticated";

grant update on table "public"."divisions" to "authenticated";

grant delete on table "public"."divisions" to "service_role";

grant insert on table "public"."divisions" to "service_role";

grant references on table "public"."divisions" to "service_role";

grant select on table "public"."divisions" to "service_role";

grant trigger on table "public"."divisions" to "service_role";

grant truncate on table "public"."divisions" to "service_role";

grant update on table "public"."divisions" to "service_role";

grant delete on table "public"."players" to "anon";

grant insert on table "public"."players" to "anon";

grant references on table "public"."players" to "anon";

grant select on table "public"."players" to "anon";

grant trigger on table "public"."players" to "anon";

grant truncate on table "public"."players" to "anon";

grant update on table "public"."players" to "anon";

grant delete on table "public"."players" to "authenticated";

grant insert on table "public"."players" to "authenticated";

grant references on table "public"."players" to "authenticated";

grant select on table "public"."players" to "authenticated";

grant trigger on table "public"."players" to "authenticated";

grant truncate on table "public"."players" to "authenticated";

grant update on table "public"."players" to "authenticated";

grant delete on table "public"."players" to "service_role";

grant insert on table "public"."players" to "service_role";

grant references on table "public"."players" to "service_role";

grant select on table "public"."players" to "service_role";

grant trigger on table "public"."players" to "service_role";

grant truncate on table "public"."players" to "service_role";

grant update on table "public"."players" to "service_role";

grant delete on table "public"."stages" to "anon";

grant insert on table "public"."stages" to "anon";

grant references on table "public"."stages" to "anon";

grant select on table "public"."stages" to "anon";

grant trigger on table "public"."stages" to "anon";

grant truncate on table "public"."stages" to "anon";

grant update on table "public"."stages" to "anon";

grant delete on table "public"."stages" to "authenticated";

grant insert on table "public"."stages" to "authenticated";

grant references on table "public"."stages" to "authenticated";

grant select on table "public"."stages" to "authenticated";

grant trigger on table "public"."stages" to "authenticated";

grant truncate on table "public"."stages" to "authenticated";

grant update on table "public"."stages" to "authenticated";

grant delete on table "public"."stages" to "service_role";

grant insert on table "public"."stages" to "service_role";

grant references on table "public"."stages" to "service_role";

grant select on table "public"."stages" to "service_role";

grant trigger on table "public"."stages" to "service_role";

grant truncate on table "public"."stages" to "service_role";

grant update on table "public"."stages" to "service_role";

grant delete on table "public"."teams" to "anon";

grant insert on table "public"."teams" to "anon";

grant references on table "public"."teams" to "anon";

grant select on table "public"."teams" to "anon";

grant trigger on table "public"."teams" to "anon";

grant truncate on table "public"."teams" to "anon";

grant update on table "public"."teams" to "anon";

grant delete on table "public"."teams" to "authenticated";

grant insert on table "public"."teams" to "authenticated";

grant references on table "public"."teams" to "authenticated";

grant select on table "public"."teams" to "authenticated";

grant trigger on table "public"."teams" to "authenticated";

grant truncate on table "public"."teams" to "authenticated";

grant update on table "public"."teams" to "authenticated";

grant delete on table "public"."teams" to "service_role";

grant insert on table "public"."teams" to "service_role";

grant references on table "public"."teams" to "service_role";

grant select on table "public"."teams" to "service_role";

grant trigger on table "public"."teams" to "service_role";

grant truncate on table "public"."teams" to "service_role";

grant update on table "public"."teams" to "service_role";

create policy "Enable insert for authenticated users only"
on "public"."tournaments"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for all users"
on "public"."tournaments"
as permissive
for select
to public
using (true);



